I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 191, in script
    h "[softly, muttering to herself] You ruined everything... you made me do this. You made me suffer. What did I do to fail you so spectacularly?"
KeyError: 'softly, muttering to herself'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 191, in script
    h "[softly, muttering to herself] You ruined everything... you made me do this. You made me suffer. What did I do to fail you so spectacularly?"
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/character.py", line 1253, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/character.py", line 1172, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/character.py", line 1152, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "/Users/mcb/Desktop/visual_novel/renpy-8.0.3-sdk/renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'softly, muttering to herself'

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
VOID 1.0
Fri Nov 18 18:15:20 2022
